# File: zephyr_zenoh_transport/west.yml
manifest:

  remotes:
    - name: ros-controls
      url-base: https://github.com/ros-controls

  projects:
    - name: zenoh-pico
      remote: ros-controls
      revision: zenbedded
      path: modules/lib/zenoh-pico
      clone-depth: 1
