CONFIG_CPP=y
CONFIG_STD_CPP17=y
CONFIG_REQUIRES_FULL_LIBC=y

CONFIG_ZENBEDDED=y
CONFIG_ZENBEDDED_TIER_2=y
CONFIG_ZENBEDDED_RCL=y
CONFIG_ZENBEDDED_RCL_PUB_TOPIC="zenbedded/inverted_pendulum/state"
CONFIG_ZENBEDDED_RCL_SUB_TOPIC="zenbedded/inverted_pendulum/cmd"

CONFIG_ZENBEDDED_QOS_RELIABLE=y
CONFIG_NET_BUF_TX_COUNT=128
CONFIG_LOG=y

CONFIG_STEPPER=y
CONFIG_GPIO=y
CONFIG_I2C=y
CONFIG_SENSOR=y
CONFIG_COUNTER=y
CONFIG_LED_STRIP=y

CONFIG_SHELL=y
CONFIG_CBPRINTF_FP_SUPPORT=y

CONFIG_ENCODER_SAMPLING_THREAD_PRIORITY=0
CONFIG_MAIN_THREAD_PRIORITY=1
CONFIG_ZENBEDDED_RCL_THREAD_PRIORITY=2

# easily toggle between USB CDC and Wi-Fi
CONFIG_INVERTED_PENDULUM_COMM_USB_CDC=y
# CONFIG_INVERTED_PENDULUM_COMM_WIFI=y
# CONFIG_ZENBEDDED_ZENOH_IP_PORT="127.0.0.1:7447"

# Disable noisy USB subsystem logging
CONFIG_UDC_DRIVER_LOG_LEVEL_OFF=y
CONFIG_USBD_LOG_LEVEL_OFF=y
CONFIG_USBD_CDC_ECM_LOG_LEVEL_OFF=y
